# Generated by Django 3.1.4 on 2020-12-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_historicoprecios_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_super',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('A', 'Administrador'), ('C', 'Cliente')], max_length=1),
        ),
    ]
