# Generated by Django 3.1.4 on 2020-12-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20201229_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='peso_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='HistoricoPrecios',
        ),
    ]
